apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-dashboards
  namespace: argocd
  labels:
    app.kubernetes.io/name: grafana-dashboards
    app.kubernetes.io/version: HEAD
    app.kubernetes.io/managed-by: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default # You may need to change this!
  source:
    path: ./
    repoURL: https://github.com/eco-heroes/grafana-dashboards
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    ## https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync
    automated:
      prune: true
      selfHeal: true
